# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('Buyer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=264)),
                ('Contact', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('Sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Delivery_Date', models.DateField()),
                ('Order_Date', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Buyer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=264)),
                ('Product_Description', models.TextField()),
                ('Reviews', models.TextField()),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Buyer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Buyer')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('Seller_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Name', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Seller_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Seller'),
        ),
    ]
