# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
