# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181015_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
